AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Indentificador de intro para VidiosPoc

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
  MyAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Runtime: python3.12
      MemorySize: 768
      Timeout: 40
      Architectures:
        - x86_64
      Environment:
        Variables:
          VIDEOS_BUCKET: aws-videos-poc
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::aws-videos-poc
                - arn:aws:s3:::aws-videos-poc/*
      Events:
        IntroEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /intro
            Method: get
            Auth:
              ApiKeyRequired: true
        CreditsEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /credits
            Method: get
            Auth:
              ApiKeyRequired: true

  MyApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: VidiosPocApiKey
      Enabled: true

  MyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: MyApiProdStage
    Properties:
      UsagePlanName: VidiosPocApiKey
      ApiStages:
        - ApiId: !Ref MyApi
          Stage: Prod
      Throttle:
        RateLimit: 20
        BurstLimit: 40
      Quota:
        Limit: 50
        Period: DAY

  MyUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref MyApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref MyUsagePlan

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"